### ISSUE TITLE
Retina显示器补丁使用

### ISSUE THREAD

**Issue by 0x0021** [zhangxuan1340/Hackintosh_E450C#2]
小白一枚，请问Retina显示器补丁怎么使用？

**Comment by zhangxuan1340** [comment]
远景论坛同ID帖子中有介绍

发自我的 iPhone

在 2019年5月7日，11:25，坤子 <notifications@github.com<mailto:notifications@github.com>> 写道：


小白一枚，请问Retina显示器补丁怎么使用？

**Comment by zhangxuan1340** [comment]
远景论坛同名ID帖子下有介绍

**Comment by zhangxuan1340** [comment]
或者你切换分支macOS14有介绍

**Comment by 0x0021** [comment]
thinks
